boutique_ado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<product_id>/', views.product_detail, name='product-detail'),
]

home/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    sku = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(null=True,blank=True, max_length=1024)
    image = models.ImageField(null=True,blank=True)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'home/index.html')

products/views.py
from django.shortcuts import (
                                render,
                                get_object_or_404,
                                redirect,
                                reverse
                            )
from django.db.models import Q
from .models import Product, Category

# Create your views here.


def all_products(request):
    products = Product.objects.all()
    query = None
    category = None
    categories = None
    sort = None
    direction = None
    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=lower('name'))
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, 'You did not enter a search query criteria')
                return redirect(reverse('products:products'))
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)
    current_sorting = f'{sort}_{direction}'
    context = {
                'products': products,
                'search_term': query,
                'current_categories': categories,
                'current_sorting': current_sorting
              }
    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    context = {'product': product}
    return render(request, 'products/product_detail.html', context)

home/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col">
                
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
 <div class="contanter h-100">
    <div class="row h-100">
        <div class="col-7 col-md-6 my-auto">
         <h1 class="display-4 logo-font text-black">The new collections are here</h1>
        </div>
        <div class="my-5">
            <a href="{% url 'products:products' %}" class="shop-now-button btn btn-lg rounded-0 text-uppercase py-3">Shop Now</a>
        </div>
    </div>
 </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col">
                
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
<div class="overlay"></div>
 <div class="contanter-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container">
                {% if product.image %}
                    <a href="{{ product.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                {% else %}
                    <a href="">
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-container mb-5 mt-md-5">
                <p class="mb-0">{{ product.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}

{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col">
                
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
<div class="overlay"></div>
 <div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
         <h2 class="logo-fonts">Products</h2>
         <hr class="w-50 mb-1">
        </div>
       
    </div>
    <div class="row">
        <div class="product-container offset-1 col-10">
        <div class="row mt-1 mb-2"></div>
        <div class="row">
            {% for product in products %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                {% if product.image %}
                                <a href="{% url 'products:product-detail' product.id %}">
                                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                </a>
                                {% else %}
                                <a href="{% url 'products:product-detail' product.id %}">
                                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                                </a>
                                {% endif %}
                                <div class="card-body pb-0">
                                    <p class="mb-0">{{ product.name }}</p>
                                </div>
                                <div class="card-footer bg-white pt-0 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                                            {% if product.rating %}
                                                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                                            {% else %}
                                                <small class="text-muted">No Rating</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                                <hr>
                            </div>
                        {% endif %}                        
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="col-12 d-none d-xl-block mb-5">
                                <hr>
                            </div>
                        {% endif %}
            {% endfor %}
        </div>
        </div>
    </div>
 </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% block meta%}
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    {% block extra_meta %}
    {% endblock %}
    {% block corecss %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&display=swap">
        <link rel="stylesheet" href="{% static '/css/base.css' %}">
    {% endblock %}
    {% block extra_css %}
    {% endblock %}
    {% block corejs %}
        <script src="https://kit.fontawesome.com/9273c684b9.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
    {% block extra_js %}
    {% endblock %}

    <title>Boutique Ado</title>
  </head>
  <body>
   <header class="container-fluid fixed-top">
    <div class="row bg-white pt-lg-2 d-none d-lg-flex" id="top">
        <div class="col-12 col-lg-4 my-auto py-1 py-lg-0 text-center text-lg-left">
            <a href="{% url 'home:home' %}" class="nav-link main-logo-link">
                <h2 class="logo-font text-black my-0"><strong>Boutique</strong>   Ado</h2>
            </a>
        </div>
        <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
            <form method="GET" action="{% url 'products:products' %}">
                <div class="input-group w-100">
                    <input class="form-control border border-black rounded-0" type="text" name="q" placeholder="Search our site">
                    <div class="input-group-append">
                        <button class="form-control btn btn-black border border-black rounded-0" type="submit">
                            <span class="icon">
                                <i class="fas fa-search"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
            <ul class="list-inline list-unstyled text-center text-lg-right my-0">
                <li class="list-inline-item dropdown">
                    <a class="text-black nav-link" href="#" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="text-center">
                            <div><i class="fas fa-user fa-lg"></i></div>
                            <p class="my-0">My Account</p>
                        </div>
                    </a>
                    <div class="dropdown-menu border-0" aria-labelledby="user-options">
                        {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}
                                <a href="" class="dropdown-item">Product Management</a>
                            {% endif %}
                            <a href="" class="dropdown-item">My Profile</a>
                            <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
                        {% else %}
                            <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
                            <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
                        {% endif %}
                    </div>
                </li>
                <li class="list-inline-item">
                    <a class="{% if grand_total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link" href="">
                        <div class="text-center">
                            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
                            <p class="my-0">
                                {% if grand_total %}
                                    ${{ grand_total|floatformat:2 }}
                                {% else %}
                                    $0.00
                                {% endif %}
                            </p>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="row bg-white">
        <nav class="navbar navbar-expand-lg navbar-light w-100">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% include 'includes/mobile_top_header.html' %}
            {% include 'includes/main_nav.html' %}
        </nav>
       
    </div>
    <div class="row text-center">
        <div class="col bg-black text-white">
            <h4 class="logo-font my-1">Free delivery on orders over ${{ free_delivery_threshold}}!</h4>
        </div>
    </div>
   </header>

   {% if messages %}
    <div class="message-container"></div>
    {% endif %}
    {% block page_header %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block postload_js %}
    {% endblock %}
  </body>
</html>

templates/includes/main_nav.html
<div class="collapse navbar-collapse" id="main-nav">
    <ul class="navbar-nav w-auto mx-auto">
        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="all-products-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                All Products
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="all-products-link">
                <a href="{% url 'products:products' %}?sort=price&direction=asc" class="dropdown-item">By Price</a>
                <a href="{% url 'products:products' %}?sort=rating&direction=desc" class="dropdown-item ">By Rating</a>
                <a href="{% url 'products:products' %}?sort=category&direction=asc" class="dropdown-item ">By Category</a>
                <a href="{% url 'products:products' %}" class="dropdown-item">All Products</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="clothing-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Clothing
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="clothing-link">
                <a href="{% url 'products:products' %}?category=activewear,essentials" class="dropdown-item">Activewear &amp; Essentials</a>
                <a href="{% url 'products:products' %}?category=jeans" class="dropdown-item">Jeans</a>
                <a href="{% url 'products:products' %}?category=shirts" class="dropdown-item">Shirts</a>
                <a href="{% url 'products:products' %}?category=activewear,essentials,jeans,shirts" class="dropdown-item">All Clothing</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="homeware-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Homeware
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="homeware-link">
                <a href="{% url 'products:products' %}?category=bed_bath" class="dropdown-item">Bed &amp; Bath</a>
                <a href="{% url 'products:products' %}?category=kitchen_dining" class="dropdown-item">Kitchen &amp; Dining</a>
                <a href="{% url 'products:products' %}?category=bed_bath,kitchen_dining" class="dropdown-item">All Homeware</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black" href="#" id="specials-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Special Offers
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="specials-link">
                <a href="{% url 'products:products' %}?category=new_arrivals" class="dropdown-item">New Arrivals</a>
                <a href="{% url 'products:products' %}?category=deals" class="dropdown-item">Deals</a>
                <a href="{% url 'products:products' %}?category=clearance" class="dropdown-item">Clearance</a>
                <a href="{% url 'products:products' %}?category=new_arrivals,deals,clearance" class="dropdown-item">All Specials</a>
            </div>
        </li>
    </ul>
</div>

templates/includes/mobile_top_header.html
<li class="list-inline-item">
    <a class="text-black nav-link d-block d-lg-none" href="#" id="mobile-search" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-search fa-lg"></i></div>
            <p class="my-0">Search</p>
        </div>
    </a>
    <div class="dropdown-menu border-0 w-100 p-3 rounded-0 my-0" aria-labelledby="mobile-search">
        <form class="form" method="GET" action="{% url 'products:products' %}">
            <div class="input-group w-100">
                <input class="form-control border border-black rounded-0" type="text" name="q" placeholder="Search our site">
                <div class="input-group-append">
                    <button class="form-control form-control btn btn-black border border-black rounded-0" type="submit">
                        <span class="icon">
                            <i class="fas fa-search"></i>
                        </span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</li>
<li class="list-inline-item dropdown">
    <a class="text-black nav-link d-block d-lg-none" href="#" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-user fa-lg"></i></div>
            <p class="my-0">My Account</p>
        </div>
    </a>
    <div class="dropdown-menu border-0" aria-labelledby="user-options">
        {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <a href="{% url 'account_logout' %}" class="dropdown-item">Product Management</a>
            {% endif %}
            <a href="#" class="dropdown-item">My Profile</a>
            <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
        {% else %}
            <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
            <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
        {% endif %}
    </div>
</li>
<li class="list-inline-item">
    <a class="{% if grand_total %}text-primary font-weight-bold{% else %}text-black{% endif %} nav-link d-block d-lg-none" href="">
        <div class="text-center">
            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
            <p class="my-0">
                {% if grand_total %}
                    ${{ grand_total|floatformat:2 }}
                {% else %}
                    $0.00
                {% endif %}
            </p>
        </div>
    </a>
</li>